export const mockCompanyDetails = {
    "Symbol": "IBM",
    "AssetType": "Common Stock",
    "Name": "International Business Machines",
    "Description": "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
    "CIK": "51143",
    "Exchange": "NYSE",
    "Currency": "USD",
    "Country": "USA",
    "Sector": "TECHNOLOGY",
    "Industry": "COMPUTER & OFFICE EQUIPMENT",
    "Address": "1 NEW ORCHARD ROAD, ARMONK, NY, US",
    "FiscalYearEnd": "December",
    "LatestQuarter": "2023-06-30",
    "MarketCapitalization": "131594813000",
    "EBITDA": "12985000000",
    "PERatio": "61.21",
    "PEGRatio": "1.276",
    "BookValue": "24.37",
    "DividendPerShare": "6.61",
    "DividendYield": "0.0463",
    "EPS": "2.36",
    "RevenuePerShareTTM": "66.75",
    "ProfitMargin": "0.0335",
    "OperatingMarginTTM": "0.141",
    "ReturnOnAssetsTTM": "0.0411",
    "ReturnOnEquityTTM": "0.104",
    "RevenueTTM": "60524999000",
    "GrossProfitTTM": "32688000000",
    "DilutedEPSTTM": "2.36",
    "QuarterlyEarningsGrowthYOY": "0.126",
    "QuarterlyRevenueGrowthYOY": "-0.004",
    "AnalystTargetPrice": "143.75",
    "TrailingPE": "61.21",
    "ForwardPE": "15.55",
    "PriceToSalesRatioTTM": "2.108",
    "PriceToBookRatio": "6.75",
    "EVToRevenue": "2.969",
    "EVToEBITDA": "25.81",
    "Beta": "0.855",
    "52WeekHigh": "149.31",
    "52WeekLow": "111.29",
    "50DayMovingAverage": "134.91",
    "200DayMovingAverage": "134.71",
    "SharesOutstanding": "911006000",
    "DividendDate": "2023-09-09",
    "ExDividendDate": "2023-08-09"
}

export const mockCurrentQuote = {
    "Global Quote": {
    "01. symbol": "IBM",
    "02. open": "141.5000",
    "03. high": "142.3100",
    "04. low": "141.2000",
    "05. price": "141.8700",
    "06. volume": "3656559",
    "07. latest trading day": "2023-08-15",
    "08. previous close": "141.9100",
    "09. change": "-0.0400",
    "10. change percent": "-0.0282%"
    }
}

export const mockSearchResults = {
    "bestMatches": [
        {
        "1. symbol": "BA",
        "2. name": "Boeing Company",
        "3. type": "Equity",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-04",
        "8. currency": "USD",
        "9. matchScore": "1.0000"
        },
        {
        "1. symbol": "BAB",
        "2. name": "Invesco Taxable Municipal Bond ETF",
        "3. type": "ETF",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-04",
        "8. currency": "USD",
        "9. matchScore": "0.8000"
        },
        {
        "1. symbol": "BA.LON",
        "2. name": "BAE Systems plc",
        "3. type": "Equity",
        "4. region": "United Kingdom",
        "5. marketOpen": "08:00",
        "6. marketClose": "16:30",
        "7. timezone": "UTC+01",
        "8. currency": "GBX",
        "9. matchScore": "0.6667"
        },
        {
        "1. symbol": "BABA",
        "2. name": "Alibaba Group Holding Ltd",
        "3. type": "Equity",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-04",
        "8. currency": "USD",
        "9. matchScore": "0.6667"
        },
        {
        "1. symbol": "BA3.FRK",
        "2. name": "Brooks Automation Inc",
        "3. type": "Equity",
        "4. region": "Frankfurt",
        "5. marketOpen": "08:00",
        "6. marketClose": "20:00",
        "7. timezone": "UTC+02",
        "8. currency": "EUR",
        "9. matchScore": "0.5714"
        },
        {
        "1. symbol": "BAAPX",
        "2. name": "BlackRock Aggressive GwthPrprdPtfInvstrA",
        "3. type": "Mutual Fund",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-04",
        "8. currency": "USD",
        "9. matchScore": "0.5714"
        },
        {
        "1. symbol": "BAAAAX",
        "2. name": "Building America Strategy Port CDA USD Ser 21/1Q MNT CASH",
        "3. type": "Mutual Fund",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-04",
        "8. currency": "USD",
        "9. matchScore": "0.5000"
        },
        {
        "1. symbol": "BAAAFX",
        "2. name": "Building America Strgy Portf CDA USD Ser 2022/2Q MNT CASH",
        "3. type": "Mutual Fund",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-04",
        "8. currency": "USD",
        "9. matchScore": "0.5000"
        },
        {
        "1. symbol": "BAB3.LON",
        "2. name": "Leverage Shares 3x Alibaba ETC",
        "3. type": "ETF",
        "4. region": "United Kingdom",
        "5. marketOpen": "08:00",
        "6. marketClose": "16:30",
        "7. timezone": "UTC+01",
        "8. currency": "USD",
        "9. matchScore": "0.5000"
        },
        {
        "1. symbol": "BAAX39.SAO",
        "2. name": "Ishares Msci All Country Asia Ex Japan ETF",
        "3. type": "ETF",
        "4. region": "Brazil/Sao Paolo",
        "5. marketOpen": "10:00",
        "6. marketClose": "17:30",
        "7. timezone": "UTC-03",
        "8. currency": "BRL",
        "9. matchScore": "0.3636"
        }
        ]
}

export const stockQuote = {
    "Global Quote": {
    "01. symbol": "IBM",
    "02. open": "143.7800",
    "03. high": "145.2200",
    "04. low": "143.3116",
    "05. price": "144.4500",
    "06. volume": "3952640",
    "07. latest trading day": "2023-08-03",
    "08. previous close": "144.1700",
    "09. change": "0.2800",
    "10. change percent": "0.1942%"
    }
}

