export const mockCompanyDetails = {
    "Symbol": "IBM",
    "AssetType": "Common Stock",
    "Name": "International Business Machines",
    "Description": "International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, the UPC barcode, and dynamic random-access memory (DRAM). The IBM mainframe, exemplified by the System/360, was the dominant computing platform during the 1960s and 1970s.",
    "CIK": "51143",
    "Exchange": "NYSE",
    "Currency": "USD",
    "Country": "USA",
    "Sector": "TECHNOLOGY",
    "Industry": "COMPUTER & OFFICE EQUIPMENT",
    "Address": "1 NEW ORCHARD ROAD, ARMONK, NY, US",
    "FiscalYearEnd": "December",
    "LatestQuarter": "2023-06-30",
    "MarketCapitalization": "131594813000",
    "EBITDA": "12985000000",
    "PERatio": "61.21",
    "PEGRatio": "1.276",
    "BookValue": "24.37",
    "DividendPerShare": "6.61",
    "DividendYield": "0.0463",
    "EPS": "2.36",
    "RevenuePerShareTTM": "66.75",
    "ProfitMargin": "0.0335",
    "OperatingMarginTTM": "0.141",
    "ReturnOnAssetsTTM": "0.0411",
    "ReturnOnEquityTTM": "0.104",
    "RevenueTTM": "60524999000",
    "GrossProfitTTM": "32688000000",
    "DilutedEPSTTM": "2.36",
    "QuarterlyEarningsGrowthYOY": "0.126",
    "QuarterlyRevenueGrowthYOY": "-0.004",
    "AnalystTargetPrice": "143.75",
    "TrailingPE": "61.21",
    "ForwardPE": "15.55",
    "PriceToSalesRatioTTM": "2.108",
    "PriceToBookRatio": "6.75",
    "EVToRevenue": "2.969",
    "EVToEBITDA": "25.81",
    "Beta": "0.855",
    "52WeekHigh": "149.31",
    "52WeekLow": "111.29",
    "50DayMovingAverage": "134.91",
    "200DayMovingAverage": "134.71",
    "SharesOutstanding": "911006000",
    "DividendDate": "2023-09-09",
    "ExDividendDate": "2023-08-09"
}

export const bestMatches = {
    "bestMatches": [
        {
        "1. symbol": "BA",
        "2. name": "Boeing Company",
        "3. type": "Equity",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-04",
        "8. currency": "USD",
        "9. matchScore": "1.0000"
        },
        {
        "1. symbol": "BAB",
        "2. name": "Invesco Taxable Municipal Bond ETF",
        "3. type": "ETF",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-04",
        "8. currency": "USD",
        "9. matchScore": "0.8000"
        },
        {
        "1. symbol": "BA.LON",
        "2. name": "BAE Systems plc",
        "3. type": "Equity",
        "4. region": "United Kingdom",
        "5. marketOpen": "08:00",
        "6. marketClose": "16:30",
        "7. timezone": "UTC+01",
        "8. currency": "GBX",
        "9. matchScore": "0.6667"
        },
        {
        "1. symbol": "BABA",
        "2. name": "Alibaba Group Holding Ltd",
        "3. type": "Equity",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-04",
        "8. currency": "USD",
        "9. matchScore": "0.6667"
        },
        {
        "1. symbol": "BA3.FRK",
        "2. name": "Brooks Automation Inc",
        "3. type": "Equity",
        "4. region": "Frankfurt",
        "5. marketOpen": "08:00",
        "6. marketClose": "20:00",
        "7. timezone": "UTC+02",
        "8. currency": "EUR",
        "9. matchScore": "0.5714"
        },
        {
        "1. symbol": "BAAPX",
        "2. name": "BlackRock Aggressive GwthPrprdPtfInvstrA",
        "3. type": "Mutual Fund",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-04",
        "8. currency": "USD",
        "9. matchScore": "0.5714"
        },
        {
        "1. symbol": "BAAAAX",
        "2. name": "Building America Strategy Port CDA USD Ser 21/1Q MNT CASH",
        "3. type": "Mutual Fund",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-04",
        "8. currency": "USD",
        "9. matchScore": "0.5000"
        },
        {
        "1. symbol": "BAAAFX",
        "2. name": "Building America Strgy Portf CDA USD Ser 2022/2Q MNT CASH",
        "3. type": "Mutual Fund",
        "4. region": "United States",
        "5. marketOpen": "09:30",
        "6. marketClose": "16:00",
        "7. timezone": "UTC-04",
        "8. currency": "USD",
        "9. matchScore": "0.5000"
        },
        {
        "1. symbol": "BAB3.LON",
        "2. name": "Leverage Shares 3x Alibaba ETC",
        "3. type": "ETF",
        "4. region": "United Kingdom",
        "5. marketOpen": "08:00",
        "6. marketClose": "16:30",
        "7. timezone": "UTC+01",
        "8. currency": "USD",
        "9. matchScore": "0.5000"
        },
        {
        "1. symbol": "BAAX39.SAO",
        "2. name": "Ishares Msci All Country Asia Ex Japan ETF",
        "3. type": "ETF",
        "4. region": "Brazil/Sao Paolo",
        "5. marketOpen": "10:00",
        "6. marketClose": "17:30",
        "7. timezone": "UTC-03",
        "8. currency": "BRL",
        "9. matchScore": "0.3636"
        }
        ]
}

export const stockQuote = {
    "Global Quote": {
    "01. symbol": "IBM",
    "02. open": "143.7800",
    "03. high": "145.2200",
    "04. low": "143.3116",
    "05. price": "144.4500",
    "06. volume": "3952640",
    "07. latest trading day": "2023-08-03",
    "08. previous close": "144.1700",
    "09. change": "0.2800",
    "10. change percent": "0.1942%"
    }
}

export const dailyHistoricalDate = {
    "Meta Data": {
    "1. Information": "Daily Prices (open, high, low, close) and Volumes",
    "2. Symbol": "IBM",
    "3. Last Refreshed": "2023-08-03",
    "4. Output Size": "Compact",
    "5. Time Zone": "US/Eastern"
    },
    "Time Series (Daily)": {
    "2023-08-03": {
    "1. open": "143.7800",
    "2. high": "145.2200",
    "3. low": "143.3116",
    "4. close": "144.4500",
    "5. volume": "3952640"
    },
    "2023-08-02": {
    "1. open": "142.7800",
    "2. high": "144.3000",
    "3. low": "142.3100",
    "4. close": "144.1700",
    "5. volume": "4959381"
    },
    "2023-08-01": {
    "1. open": "144.2500",
    "2. high": "144.4800",
    "3. low": "142.1700",
    "4. close": "143.3300",
    "5. volume": "4798703"
    },
    "2023-07-31": {
    "1. open": "143.8100",
    "2. high": "144.6050",
    "3. low": "143.5300",
    "4. close": "144.1800",
    "5. volume": "6138902"
    },
    "2023-07-28": {
    "1. open": "143.4400",
    "2. high": "143.9500",
    "3. low": "142.8500",
    "4. close": "143.4500",
    "5. volume": "6686627"
    },
    "2023-07-27": {
    "1. open": "142.3000",
    "2. high": "143.3800",
    "3. low": "141.9000",
    "4. close": "142.9700",
    "5. volume": "6331563"
    },
    "2023-07-26": {
    "1. open": "140.4400",
    "2. high": "141.2500",
    "3. low": "139.8800",
    "4. close": "141.0700",
    "5. volume": "4046441"
    },
    "2023-07-25": {
    "1. open": "139.4200",
    "2. high": "140.4300",
    "3. low": "139.0403",
    "4. close": "140.3300",
    "5. volume": "3770813"
    },
    "2023-07-24": {
    "1. open": "139.3500",
    "2. high": "140.1200",
    "3. low": "138.7788",
    "4. close": "139.5400",
    "5. volume": "3475442"
    },
    "2023-07-21": {
    "1. open": "138.2100",
    "2. high": "139.7799",
    "3. low": "137.7600",
    "4. close": "138.9400",
    "5. volume": "5858741"
    },
    "2023-07-20": {
    "1. open": "137.1900",
    "2. high": "140.3200",
    "3. low": "136.5600",
    "4. close": "138.3800",
    "5. volume": "10896330"
    },
    "2023-07-19": {
    "1. open": "135.5300",
    "2. high": "136.4500",
    "3. low": "135.1900",
    "4. close": "135.4800",
    "5. volume": "5519992"
    },
    "2023-07-18": {
    "1. open": "134.7100",
    "2. high": "135.9500",
    "3. low": "134.2900",
    "4. close": "135.3600",
    "5. volume": "3852058"
    },
    "2023-07-17": {
    "1. open": "133.2600",
    "2. high": "134.6100",
    "3. low": "133.1000",
    "4. close": "134.2400",
    "5. volume": "3168419"
    },
    "2023-07-14": {
    "1. open": "133.9100",
    "2. high": "133.9200",
    "3. low": "132.9400",
    "4. close": "133.4000",
    "5. volume": "2861496"
    },
    "2023-07-13": {
    "1. open": "133.5100",
    "2. high": "135.0700",
    "3. low": "133.3600",
    "4. close": "133.9200",
    "5. volume": "3221422"
    },
    "2023-07-12": {
    "1. open": "135.0700",
    "2. high": "135.3300",
    "3. low": "132.5750",
    "4. close": "132.8400",
    "5. volume": "3732189"
    },
    "2023-07-11": {
    "1. open": "133.6600",
    "2. high": "134.5600",
    "3. low": "133.2300",
    "4. close": "134.4400",
    "5. volume": "2925238"
    },
    "2023-07-10": {
    "1. open": "131.7600",
    "2. high": "133.0500",
    "3. low": "131.6950",
    "4. close": "132.9000",
    "5. volume": "2369425"
    },
    "2023-07-07": {
    "1. open": "131.7800",
    "2. high": "133.8550",
    "3. low": "131.7500",
    "4. close": "132.0800",
    "5. volume": "2982738"
    },
    "2023-07-06": {
    "1. open": "133.2350",
    "2. high": "133.9000",
    "3. low": "131.5500",
    "4. close": "132.1600",
    "5. volume": "3508083"
    },
    "2023-07-05": {
    "1. open": "133.3200",
    "2. high": "134.3100",
    "3. low": "132.5900",
    "4. close": "134.2400",
    "5. volume": "2955870"
    },
    "2023-07-03": {
    "1. open": "133.4200",
    "2. high": "134.3500",
    "3. low": "132.8700",
    "4. close": "133.6700",
    "5. volume": "1477149"
    },
    "2023-06-30": {
    "1. open": "134.6900",
    "2. high": "135.0300",
    "3. low": "133.4250",
    "4. close": "133.8100",
    "5. volume": "4236677"
    },
    "2023-06-29": {
    "1. open": "131.7500",
    "2. high": "134.3500",
    "3. low": "131.6900",
    "4. close": "134.0600",
    "5. volume": "3639836"
    },
    "2023-06-28": {
    "1. open": "132.0600",
    "2. high": "132.1700",
    "3. low": "130.9100",
    "4. close": "131.7600",
    "5. volume": "2753779"
    },
    "2023-06-27": {
    "1. open": "131.3000",
    "2. high": "132.9500",
    "3. low": "130.8300",
    "4. close": "132.3400",
    "5. volume": "3219909"
    },
    "2023-06-26": {
    "1. open": "129.3900",
    "2. high": "131.4100",
    "3. low": "129.3100",
    "4. close": "131.3400",
    "5. volume": "4845649"
    },
    "2023-06-23": {
    "1. open": "130.4000",
    "2. high": "130.6200",
    "3. low": "129.1800",
    "4. close": "129.4300",
    "5. volume": "11324705"
    },
    "2023-06-22": {
    "1. open": "131.6800",
    "2. high": "132.9600",
    "3. low": "130.6800",
    "4. close": "131.1700",
    "5. volume": "6013021"
    },
    "2023-06-21": {
    "1. open": "135.1100",
    "2. high": "135.3900",
    "3. low": "133.2900",
    "4. close": "133.6900",
    "5. volume": "5501272"
    },
    "2023-06-20": {
    "1. open": "136.3600",
    "2. high": "137.2300",
    "3. low": "135.8900",
    "4. close": "135.9600",
    "5. volume": "4272511"
    },
    "2023-06-16": {
    "1. open": "139.2300",
    "2. high": "139.4690",
    "3. low": "137.4700",
    "4. close": "137.4800",
    "5. volume": "7473676"
    },
    "2023-06-15": {
    "1. open": "137.2700",
    "2. high": "138.8000",
    "3. low": "137.1750",
    "4. close": "138.4000",
    "5. volume": "3812582"
    },
    "2023-06-14": {
    "1. open": "137.8000",
    "2. high": "138.9300",
    "3. low": "136.9400",
    "4. close": "137.2000",
    "5. volume": "4514888"
    },
    "2023-06-13": {
    "1. open": "136.5100",
    "2. high": "138.1700",
    "3. low": "136.0000",
    "4. close": "137.6000",
    "5. volume": "3927331"
    },
    "2023-06-12": {
    "1. open": "136.0000",
    "2. high": "136.6200",
    "3. low": "135.8216",
    "4. close": "136.4200",
    "5. volume": "4500120"
    },
    "2023-06-09": {
    "1. open": "134.3600",
    "2. high": "136.1000",
    "3. low": "134.1700",
    "4. close": "135.3000",
    "5. volume": "3981748"
    },
    "2023-06-08": {
    "1. open": "134.6900",
    "2. high": "135.9800",
    "3. low": "134.0100",
    "4. close": "134.4100",
    "5. volume": "4128939"
    },
    "2023-06-07": {
    "1. open": "132.5000",
    "2. high": "134.4400",
    "3. low": "132.1900",
    "4. close": "134.3800",
    "5. volume": "5772024"
    },
    "2023-06-06": {
    "1. open": "132.4300",
    "2. high": "132.9400",
    "3. low": "131.8800",
    "4. close": "132.6900",
    "5. volume": "3297951"
    },
    "2023-06-05": {
    "1. open": "133.1200",
    "2. high": "133.5800",
    "3. low": "132.2700",
    "4. close": "132.6400",
    "5. volume": "3993516"
    },
    "2023-06-02": {
    "1. open": "130.3800",
    "2. high": "133.1200",
    "3. low": "130.1500",
    "4. close": "132.4200",
    "5. volume": "5375796"
    },
    "2023-06-01": {
    "1. open": "128.4400",
    "2. high": "130.1450",
    "3. low": "127.7800",
    "4. close": "129.8200",
    "5. volume": "4136086"
    },
    "2023-05-31": {
    "1. open": "128.5100",
    "2. high": "129.4400",
    "3. low": "127.4600",
    "4. close": "128.5900",
    "5. volume": "11086313"
    },
    "2023-05-30": {
    "1. open": "129.5600",
    "2. high": "130.0699",
    "3. low": "128.2600",
    "4. close": "129.4800",
    "5. volume": "3741050"
    },
    "2023-05-26": {
    "1. open": "127.0600",
    "2. high": "129.6600",
    "3. low": "126.8100",
    "4. close": "128.8900",
    "5. volume": "5612570"
    },
    "2023-05-25": {
    "1. open": "125.6100",
    "2. high": "127.2300",
    "3. low": "125.0100",
    "4. close": "126.7600",
    "5. volume": "4102854"
    },
    "2023-05-24": {
    "1. open": "127.8200",
    "2. high": "127.9000",
    "3. low": "125.4700",
    "4. close": "125.6800",
    "5. volume": "3915505"
    },
    "2023-05-23": {
    "1. open": "127.2400",
    "2. high": "129.0900",
    "3. low": "127.1300",
    "4. close": "128.1800",
    "5. volume": "4592280"
    },
    "2023-05-22": {
    "1. open": "127.5000",
    "2. high": "128.1900",
    "3. low": "127.1500",
    "4. close": "127.5000",
    "5. volume": "2806770"
    },
    "2023-05-19": {
    "1. open": "126.7900",
    "2. high": "128.2900",
    "3. low": "126.5500",
    "4. close": "127.2600",
    "5. volume": "4306657"
    },
    "2023-05-18": {
    "1. open": "125.3000",
    "2. high": "126.5100",
    "3. low": "125.1894",
    "4. close": "126.1500",
    "5. volume": "3797883"
    },
    "2023-05-17": {
    "1. open": "123.9400",
    "2. high": "125.8500",
    "3. low": "123.4700",
    "4. close": "125.7100",
    "5. volume": "4515134"
    },
    "2023-05-16": {
    "1. open": "123.3500",
    "2. high": "123.8600",
    "3. low": "122.4500",
    "4. close": "123.4600",
    "5. volume": "2749125"
    },
    "2023-05-15": {
    "1. open": "123.0000",
    "2. high": "123.6881",
    "3. low": "122.3400",
    "4. close": "123.3600",
    "5. volume": "2915725"
    },
    "2023-05-12": {
    "1. open": "121.4100",
    "2. high": "122.8600",
    "3. low": "121.1100",
    "4. close": "122.8400",
    "5. volume": "4564825"
    },
    "2023-05-11": {
    "1. open": "122.0200",
    "2. high": "122.2400",
    "3. low": "120.5500",
    "4. close": "120.9000",
    "5. volume": "3446452"
    },
    "2023-05-10": {
    "1. open": "121.9900",
    "2. high": "122.4900",
    "3. low": "121.1000",
    "4. close": "122.0200",
    "5. volume": "4189222"
    },
    "2023-05-09": {
    "1. open": "121.9000",
    "2. high": "121.9700",
    "3. low": "120.6600",
    "4. close": "121.1700",
    "5. volume": "4540047"
    },
    "2023-05-08": {
    "1. open": "123.7600",
    "2. high": "123.9200",
    "3. low": "122.5500",
    "4. close": "123.4000",
    "5. volume": "3663818"
    },
    "2023-05-05": {
    "1. open": "123.1100",
    "2. high": "124.1000",
    "3. low": "122.8050",
    "4. close": "123.6500",
    "5. volume": "4971936"
    },
    "2023-05-04": {
    "1. open": "123.0300",
    "2. high": "123.5200",
    "3. low": "121.7563",
    "4. close": "122.5700",
    "5. volume": "4468237"
    },
    "2023-05-03": {
    "1. open": "125.4600",
    "2. high": "125.5700",
    "3. low": "123.2600",
    "4. close": "123.4500",
    "5. volume": "4554212"
    },
    "2023-05-02": {
    "1. open": "126.3000",
    "2. high": "126.4500",
    "3. low": "123.2700",
    "4. close": "125.1600",
    "5. volume": "4445283"
    },
    "2023-05-01": {
    "1. open": "126.3500",
    "2. high": "126.7500",
    "3. low": "126.0600",
    "4. close": "126.0900",
    "5. volume": "2724992"
    },
    "2023-04-28": {
    "1. open": "126.5800",
    "2. high": "127.2500",
    "3. low": "125.6400",
    "4. close": "126.4100",
    "5. volume": "5061247"
    },
    "2023-04-27": {
    "1. open": "126.3700",
    "2. high": "127.0200",
    "3. low": "125.4550",
    "4. close": "126.9700",
    "5. volume": "3204889"
    },
    "2023-04-26": {
    "1. open": "125.8100",
    "2. high": "126.5450",
    "3. low": "125.1200",
    "4. close": "125.8500",
    "5. volume": "4058800"
    },
    "2023-04-25": {
    "1. open": "124.9000",
    "2. high": "126.1900",
    "3. low": "124.7600",
    "4. close": "125.8900",
    "5. volume": "4275396"
    },
    "2023-04-24": {
    "1. open": "125.5500",
    "2. high": "126.0500",
    "3. low": "124.5600",
    "4. close": "125.4000",
    "5. volume": "4043892"
    },
    "2023-04-21": {
    "1. open": "126.0000",
    "2. high": "126.7000",
    "3. low": "125.2700",
    "4. close": "125.7300",
    "5. volume": "6725426"
    },
    "2023-04-20": {
    "1. open": "130.1500",
    "2. high": "130.9800",
    "3. low": "125.8400",
    "4. close": "126.3600",
    "5. volume": "9749618"
    },
    "2023-04-19": {
    "1. open": "126.5000",
    "2. high": "126.9800",
    "3. low": "125.3000",
    "4. close": "126.3200",
    "5. volume": "7014368"
    },
    "2023-04-18": {
    "1. open": "128.1400",
    "2. high": "128.6800",
    "3. low": "127.3500",
    "4. close": "127.7800",
    "5. volume": "3193787"
    },
    "2023-04-17": {
    "1. open": "128.3000",
    "2. high": "128.7200",
    "3. low": "126.8000",
    "4. close": "127.8200",
    "5. volume": "3657929"
    },
    "2023-04-14": {
    "1. open": "128.4600",
    "2. high": "129.8400",
    "3. low": "127.3100",
    "4. close": "128.1400",
    "5. volume": "4180614"
    },
    "2023-04-13": {
    "1. open": "128.0100",
    "2. high": "128.3900",
    "3. low": "126.0000",
    "4. close": "127.9000",
    "5. volume": "5621512"
    },
    "2023-04-12": {
    "1. open": "130.4000",
    "2. high": "130.8857",
    "3. low": "128.1700",
    "4. close": "128.5400",
    "5. volume": "3957542"
    },
    "2023-04-11": {
    "1. open": "130.5800",
    "2. high": "131.1050",
    "3. low": "130.1800",
    "4. close": "130.4200",
    "5. volume": "3132430"
    },
    "2023-04-10": {
    "1. open": "129.8300",
    "2. high": "131.0800",
    "3. low": "129.2400",
    "4. close": "131.0300",
    "5. volume": "2614402"
    },
    "2023-04-06": {
    "1. open": "132.1600",
    "2. high": "132.6000",
    "3. low": "130.3150",
    "4. close": "130.5000",
    "5. volume": "3050581"
    },
    "2023-04-05": {
    "1. open": "131.3700",
    "2. high": "132.6100",
    "3. low": "131.3700",
    "4. close": "132.1400",
    "5. volume": "2898759"
    },
    "2023-04-04": {
    "1. open": "131.9900",
    "2. high": "132.1499",
    "3. low": "130.8900",
    "4. close": "131.6000",
    "5. volume": "3382783"
    },
    "2023-04-03": {
    "1. open": "130.9700",
    "2. high": "132.6100",
    "3. low": "130.7700",
    "4. close": "132.0600",
    "5. volume": "3840139"
    },
    "2023-03-31": {
    "1. open": "129.4700",
    "2. high": "131.2300",
    "3. low": "129.4200",
    "4. close": "131.0900",
    "5. volume": "4524686"
    },
    "2023-03-30": {
    "1. open": "130.1600",
    "2. high": "131.4800",
    "3. low": "129.1000",
    "4. close": "129.2200",
    "5. volume": "3561762"
    },
    "2023-03-29": {
    "1. open": "130.1200",
    "2. high": "130.3500",
    "3. low": "129.1800",
    "4. close": "129.7100",
    "5. volume": "3279846"
    },
    "2023-03-28": {
    "1. open": "129.1800",
    "2. high": "129.6600",
    "3. low": "128.8000",
    "4. close": "129.3400",
    "5. volume": "2889115"
    },
    "2023-03-27": {
    "1. open": "126.4700",
    "2. high": "130.2550",
    "3. low": "126.4700",
    "4. close": "129.3100",
    "5. volume": "6524113"
    },
    "2023-03-24": {
    "1. open": "123.3600",
    "2. high": "125.4000",
    "3. low": "122.8800",
    "4. close": "125.2900",
    "5. volume": "3812644"
    },
    "2023-03-23": {
    "1. open": "123.8100",
    "2. high": "124.9300",
    "3. low": "122.6000",
    "4. close": "123.3700",
    "5. volume": "4651936"
    },
    "2023-03-22": {
    "1. open": "127.0000",
    "2. high": "127.2150",
    "3. low": "124.0100",
    "4. close": "124.0500",
    "5. volume": "3549024"
    },
    "2023-03-21": {
    "1. open": "126.9000",
    "2. high": "127.1500",
    "3. low": "125.6600",
    "4. close": "126.5700",
    "5. volume": "3856345"
    },
    "2023-03-20": {
    "1. open": "124.3100",
    "2. high": "126.1600",
    "3. low": "124.1900",
    "4. close": "125.9400",
    "5. volume": "4588304"
    },
    "2023-03-17": {
    "1. open": "124.0800",
    "2. high": "124.5200",
    "3. low": "122.9300",
    "4. close": "123.6900",
    "5. volume": "37400167"
    },
    "2023-03-16": {
    "1. open": "122.9600",
    "2. high": "124.8200",
    "3. low": "121.9200",
    "4. close": "124.7000",
    "5. volume": "6440023"
    },
    "2023-03-15": {
    "1. open": "122.9900",
    "2. high": "123.3500",
    "3. low": "121.7100",
    "4. close": "123.2800",
    "5. volume": "5989339"
    },
    "2023-03-14": {
    "1. open": "126.4900",
    "2. high": "126.6400",
    "3. low": "123.2000",
    "4. close": "124.6500",
    "5. volume": "8114792"
    },
    "2023-03-13": {
    "1. open": "125.1500",
    "2. high": "128.1900",
    "3. low": "124.8500",
    "4. close": "125.5800",
    "5. volume": "8188369"
    }
    
}
}